### PR TITLE
Two minor fixes and one major one related to share merge

### PR DESCRIPTION
**Pull request by MoneroOcean**
This pull request contains 3 fixes:

1) Obvious nicehash difficulty fix.
2) Simple fix for underscores in email worker names.
3) Major fix related to recordShareData accumulation that aims to solve LMDB scalability problem that I hope at least will be reviewed.

### CODE REVIEW

**Comment by MoneroOcean** [comment]
Note for share merge: it is true that accumulated shares will be delayed by around one minute and if miner will completely stop submitting shares for his wallet then his accumulated shares for last minute will be not submitted (until he will start mining again on this leaf/thread). This can affect PPLNS profit calculations however I consider these effects to be negligible because normally PPNLS window is several hours long and this effect will not significantly benefit any particular group of miners, so positive value of this change in terms of avoiding LMDB/network overload (that will affect miners more gravely actually) is more important IMHO.

**Comment by MoneroOcean** [comment]
BTW. I might be wrong but is not that true that blockPayments (that do reward calculations for PPS/PPLNS) is called after 60 blocks (or some other non zero value) passed? That means that for reward calculations all shares should be already in DB since likely that time will exceed 1 minute.

**Comment by Snipa22** [comment]
Correct, but that's not the concern.  Currently, the system processes the shares in a linear order, with the oldest share being at the top of the block storage.  With this, the system now "spools" miners, causing the following:

During the last block, 4 miners participate, with shares that look like:
First 60 seconds: 1|2|3|4|2|3|4|1|2
Second 60 seconds: 1|3|2|3|1|3|4|2|1
With the change, assuming it does two submissions, it now looks like:
1|2|3|4|1|3|2|4
Versus:
1|2|3|4|2|3|4|1|2|1|3|2|3|1|3|4|2|5

This means that if miner 1 found the block on a particularly high diff near the end, as he's the obvious finder, he may lock out the shares of 2, 3, and 4, as the diff of his summed shares may exceed the shares required to finish out the block, unfairly locking out payments.

**Comment by MoneroOcean** [comment]
I see. I think the situation you described is because of this "if" clause that immediately writes share with block candidate:

    if (blockCandidate) {
-        foundBlock: blockCandidate,
+
-        trustedShare: shareType,
+        global.database.storeShare(job.height, global.protos.Share.encode({
-        poolType: miner.poolTypeEnum,
+            shares: job.difficulty,
-        poolID: global.config.pool_id,
+            paymentAddress: miner.address,
-        blockDiff: activeBlockTemplate.difficulty,
+            paymentID: miner.paymentID,
-        bitcoin: miner.bitcoin,
+            foundBlock: blockCandidate,
-        blockHeight: job.height,
+            trustedShare: shareType,
-        timestamp: Date.now(),
+            poolType: miner.poolTypeEnum,
-        identifier: miner.identifier
+            poolID: global.config.pool_id,
-    }));
+            blockDiff: activeBlockTemplate.difficulty,
+            bitcoin: miner.bitcoin,
+            blockHeight: job.height,
+            timestamp: Date.now(),
+            identifier: safe_worker_name
+        }));
+
+    } else {

What if we remove this clause and just lease its "else" compound statement?

**Comment by Snipa22** [comment]
The paste came through terribly, but it doesn't fix it by merely submitting the miner's shares immediately.  PPLNS is based on paying out per share, not by grouping per address over a time period.  It also doesn't resolve the stats issue in the slightest.

**Comment by MoneroOcean** [comment]
Got it. What if we will add extra condition for share submission that accumulated share should not exceed let's say 1000000 hashes?

**Comment by Snipa22** [comment]
1m hashes is pretty easy to hit for large farms (And/or proxies).  I'd much rather see these efforts directed at fixing the backend (Removing LMDB), which is what we've done for SupportXMR at this point.  IIRC, HashVault has been working on replacing his with MongoDB.  There's been two large things I've noticed with the way Monero has changed in terms of mining, neither of which was a big deal when the pool was developed:
1. Web mining is becoming much more prolific, causing massive numbers of low-value shares, causing transaction issues in LMDB.  SupportXMR for example, is now handling 250m+ shares a day at this point, or right around 3k transaction/second.
2. Botnets have become much more aggressive, and refuse to use the proxy/etc.  LMDB was not designed for this type of transactional load as near as I can tell, due to the single-writer policies/etc.  It's fine for small, high diff setups, but the number of small miners that have increased load across the network is starting to cause major problems.

**Comment by MoneroOcean** [comment]
I think that these challenges require improvements on several layers - not only DB layer improvements (which are of course also important but unfortunately not open sourced at this point). The proposed solution aims to prevent the problem with low diff shares before they even start causing problems in the DB (or network channel between pool and leaf node).

In any case thank you for review. I really improved the code based on your input. If you will still consider that this code can be integrated to the main trunk after some improvements I will gladly work on them.

**Pull request closed without merging**
