### PR TITLE
Improve error management when interacting with coin daemon.

### PR DESCRIPTION
**Pull request by adaxi**
`getBlockTemplate` now returns an error when the RPC does not contain a result.

Checking for a callback error is done: `if (err) { ... }` instead of `if (err !== null) { ... }`

The worker now sends an email when it cannot get last block height when checking if server is behind in blocks. This solves my issue where I received an email indicating that I was `NaN blocks behind`

I renamed `getBlockHeaderByID` to `getBlockHeaderByHeight` to match the RPC request name. Also this function is not used at the moment anywhere else in the code.

### CODE REVIEW

**Comment by bobbieltd** [comment]
Ouff, my opinions :
1. I don’t like ? operator, it looks difficult to understand
2. ID/Height is both OK.
3. RPC does not contain a result. What is type of RPC ?
4. I guess your pools are not XMR or AEON.
I’m curious too.

**Comment by adaxi** [comment]
Hi, 

1. I like the `?` operator a lot, especially when using arrow functions since it can really simplify the code.
```js
function (condition) {
  if (condition) {
    return 'Y';
  } else {
    return 'X';
  } 
}
```
becomes:
```js
condition => condition ? 'Y' : 'X';
```
Once you get used to it, you start appreciating it.

2. Since ID and Height are synonyms I think is preferable to match the nomenclature exposed by the deamons which is `'getblockheaderbyheight'`. I took the liberty of doing it because this function is not used anywhere else in the code.

3. The RPC in question was: 'getblocktemplate'. You can see that it was directly returning the reponse body without any checks.
It was validating that request was valid in `lib/pool.js` (line 159). This pull request moves this validation to the coin file, as it is done for other RPC requests.

4. My pool is XMR. Why do you ask?

**Comment by bobbieltd** [comment]
Your way of shortening codes by operator makes me or other newbies difficulty to understand the code. It’s only good if most are IT guys. With Snipa’s codes, I can understand a bit but with your codes, I feel dump. If you want to follow coin RPC documentation, I guess we should check rpcresult.status , don’t we ?
I ask which coin because most don’t have this issue with XMR/AEON. I plan to make pools with other coins, I want to know just in case I need to fix the codes.
It seems you know codes very well. I hope that you’ll contribute more works to Snipa’s repo (without shortening codes will be best :) ).

**Comment by adaxi** [comment]
Javascript is evolving, the industry is moving to ES6. There is a lot of [tutorials](http://ccoenraets.github.io/es6-tutorial/let/) and [guides](https://learn.co/lessons/introduction-to-es6) that help you understand the changes. It is a good opportunity to learn new things!

Using the `status` is indeed a good improvement. Nonetheless the `status` field is not returned when the RCP fails. On the other hand we could also check for the `error` field.

This pull request does not fix a bug. This only makes the code more robust and less prone to failures.

**Comment by TwixtedChaox** [comment]
I agree with you there... seperate to notification for one pr ny itself... thats the part i plan on implementing

**Comment by adaxi** [comment]
I agree with you when you say it is a bit of an over-reach, I could try to submit smaller pull requests (perhaps better for review purposes), but in the end the result would be approximately the same.

I use `if (!err)`  instead of `if (err !== null)` because some libraries will return `undefined` instead of `null`. In that case the code checking for not `null` will return unexpected results.

Sure the code base might need some improvements, but are you sure you want to go through a full rewrite? I honestly think that cleaning the code bit by bit, and introducing some linters can do wonders.

**Comment by Snipa22** [comment]
All, of the !== null checks are internal against my own code base, which is why I'm fine with those checks, and avoids the possibility of odd type-casting, which I tend to prefer.  Past that, I do happen to agree with the comments on the ternary ops.  While I'm perfectly fine reading them, this project was not designed for high level developers to work with, it's designed for people whom are interested in the pool to be able to edit and modify, and ternary ops are not the simplest thing.  I'd lean towards leaving the if/else conditionals personally, but people are welcome to comment either way.

**Comment by adaxi** [comment]
Thank you for your input.

I am closing this pull request and will provide simpler pull requests.

**Pull request closed without merging**
