### PR TITLE
ETN coin support

### PR DESCRIPTION
**Pull request by ArqTras**

### CODE REVIEW

**Comment by ArqTras** [comment]
Correct wallet identification for etn coin

**Comment by bobbieltd** [comment]
Did you test with ETN ? Does it work ?

**Comment by ArqTras** [comment]
Work for me but still testing

**Comment by Snipa22** [comment]
ETN changes need to be seperated from the rest of the base configuration, SQL, etc.  Changes to the main .sql files and .json files will cause this to be non-accepted.

**Comment by ArqTras** [comment]
I understand that the master must be universal, I can improve, but is not it better to add branch etn?

**Comment by Snipa22** [comment]
This is a merge request into the master branch, If you're adding heavy multi-coin support, it's better to setup a different set of folders for deployments.

**Comment by ArqTras** [comment]
I understand in that case, I will prepare a version that does not interfere with the master

**Pull request closed without merging**
